services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  auth-service:
    build:  
      context: ./auth-server
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always 
    env_file:
      - ./auth-server/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./auth-server/cmd/config.yaml:/app/cmd/config.yaml
    networks:
      - backend
  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    env_file:
      - ./user/.env
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - backend

  chat-service:
    build:
      context: ./chat
      dockerfile: Dockerfile
    container_name: chat-service
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend

  discount-service:
    build:
      context: ./discount
      dockerfile: Dockerfile
    container_name: discount-service
    restart: always
    ports:
      - "8082:8080"
    networks:
      - backend
volumes:
  pgdata:

networks:
  backend:
    driver: bridge