db:
  host: postgres  
  port: 5432
  user: postgres
  password: 123456
  name: user-api
  sslmode: disable

redis:
  addr: "redis:6379"
  password: ""
  db: 0

jwt:
  secret: "your_jwt_secret_key"
  expiration: 60

server:
  port: ":8080"
